name: CI

# Triggers the workflow on all pushes.
on: push

jobs:
  # Main test job.
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install deps
      run: |
        . ./.env
        yarn

    - name: Run the tests
      run: |
        . ./.env
        yarn test

    - name: Test coverage
      run: |
        . ./.env
        yarn coverage

    - name: Upload coverage report
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: ./coverage.json
        verbose: true
